output "kubectl_config" {
  description = "kubectl config generated by the EKS module"
  value       = module.eks.kubeconfig
}

output "rds_instance_addresss" {
  description = "RDS instance address"
  value = module.rds_postgres_weblate.this_db_instance_address
}

data "aws_caller_identity" "current" {}

output "account_id" {
  value = "${data.aws_caller_identity.current.account_id}"
}
