apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "weblate.fullname" . }}
  labels:
{{ include "weblate.labels" . | indent 4 }}
data:
  settings-override.py: {{ toYaml .Values.configOverride | indent 2 }}
