apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "weblate.fullname" . }}
  labels: {{- include "weblate.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "weblate.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "weblate.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "weblate.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "weblate.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
            limits:
              memory: "1024Mi"
              cpu: "200m"
          env:
            - name: POSTGRES_DATABASE
              value: "{{ .Values.postgresql.postgresqlDatabase }}"
            - name: POSTGRES_HOST
              value: "{{ .Values.postgresql.endpoint }}"
            - name: POSTGRES_PORT
              value: "{{ .Values.postgresql.port }}"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "weblate.fullname" . }}
                  key: postgresql-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "weblate.fullname" . }}
                  key: postgresql-password
            - name: REDIS_HOST
              value: {{ .Release.Name }}-redis-master
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "weblate.fullname" . }}
                  key: redis-password
            - name: WEBLATE_ADMIN_EMAIL
              value: "{{ .Values.adminEmail }}"
            - name: WEBLATE_ADMIN_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "weblate.fullname" . }}
                  key: admin-user
            - name: WEBLATE_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "weblate.fullname" . }}
                  key: admin-password
            - name: WEBLATE_EMAIL_HOST
              value: "{{ .Values.emailHost }}"
            - name: WEBLATE_EMAIL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "weblate.fullname" . }}
                  key: email-user
            - name: WEBLATE_EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "weblate.fullname" . }}
                  key: email-password
            - name: WEBLATE_SERVER_EMAIL
              value: "{{ .Values.serverEmail }}"
            - name: WEBLATE_DEFAULT_FROM_EMAIL
              value: "{{ .Values.defaultFromEmail }}"
            - name: WEBLATE_ALLOWED_HOSTS
              value: "{{ .Values.allowedHosts }}"
            - name: WEBLATE_DEBUG
              value: "{{ .Values.debug }}"
            - name: CELERY_TASK_ALWAYS_EAGER
              value: "False"
            - name: CELERY_BROKER_URL
              value: "amqp://{{ index .Values "rabbitmq-ha" "rabbitmqUsername" }}:{{ index .Values "rabbitmq-ha" "rabbitmqPassword" }}@{{ .Release.Name }}-rabbitmq-ha"
            - name: CELERY_RESULT_BACKEND
              value: "amqp://{{ index .Values "rabbitmq-ha" "rabbitmqUsername" }}:{{ index .Values "rabbitmq-ha" "rabbitmqPassword" }}@{{ .Release.Name }}-rabbitmq-ha"
            {{- range $key, $value := .Values.extraConfig }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: weblate-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
